 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: {{APP_NAME}}
 spec:
   tls:
   - hosts:
     - {{APP_NAME}}.{{CLUSTER_HOST}}
   rules:
   - host: {{APP_NAME}}.{{CLUSTER_HOST}}
     http:
       paths:
       - path: /
         backend:
           serviceName: {{APP_NAME}}
           servicePort: 80
